'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18449
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Builder.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property res() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("res", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [MRU List]
        '''MRU1=D:\Documents and Settings\Administrateur\Bureau\KingCobraXD Assembly Changer\KingCobraXD Assembly Changer\Resources\Res.exe
        '''MRU2=
        '''MRU3=
        '''MRU4=
        '''
        '''[Setup]
        '''left=235
        '''top=248
        '''width=681
        '''height=367
        '''MaximizedState=0
        '''vsplit=200
        '''LastOpenedDir=D:\Documents and Settings\Administrateur\Bureau\KingCobraXD Assembly Changer\KingCobraXD Assembly Changer\Resources
        '''LastSavedDir=
        '''
        '''[Font]
        '''Name=Courier New
        '''Size=10
        '''CharSet=1
        '''Color=-2147483640
        '''Style=0
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property Res1() As String
            Get
                Return ResourceManager.GetString("Res1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System.Windows.Forms
        '''Imports System.Reflection
        '''
        '''&lt;Assembly: AssemblyTitle(&quot;1&quot;)&gt; 
        '''&lt;Assembly: AssemblyDescription(&quot;2&quot;)&gt; 
        '''&lt;Assembly: AssemblyCompany(&quot;3&quot;)&gt; 
        '''&lt;Assembly: AssemblyProduct(&quot;4&quot;)&gt; 
        '''&lt;Assembly: AssemblyCopyright(&quot;Copyright ©  2014 &quot; &amp; &quot; 5&quot;)&gt; 
        '''&lt;Assembly: AssemblyTrademark(&quot;6&quot;)&gt; 
        '''&lt;Assembly: AssemblyVersion(&quot;*version*&quot;)&gt; 
        '''&lt;Assembly: AssemblyFileVersion(&quot;*fversion*&quot;)&gt; 
        '''
        '''Module X
        '''    Sub Main()
        '''    	MessageBox.Show(&quot;&quot;, &quot;&quot;, MessageBoxButtons.OK, MessageBoxIcon.Error)
        '''    End Sub
        '''End Mod [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
