'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Taakj2005_3rd_Brain_Tech_VBS_Encrypter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to on error resume next
        '''
        ''' function dgfvhjfvhjefef(dfdsfdsfsdfggg) 
        '''if &quot;rnku7rgb91&quot; = iazzmibmcw then
        '''Mid &quot;llhxczoigb&quot;,5,6 
        '''else
        '''Mid &quot;pjxcjontyc&quot;,9,9 
        '''end if
        '''  dim yohujfxpfy, lmrstve, fdfsdraea 
        '''
        '''  yohujfxpfy = &quot;&quot; 
        '''
        '''  for lmrstve = 2 to Len(dfdsfdsfsdfggg) 
        '''
        '''   fdfsdraea = &quot;&quot; 
        '''
        '''   while Mid(dfdsfdsfsdfggg, lmrstve, 1) &lt;&gt;  chrw(1.45238095238095 * 42)   and lmrstve &lt;= Len(dfdsfdsfsdfggg) 
        '''
        '''    fdfsdraea = fdfsdraea + Mid(dfdsfdsfsdfggg, lmrstve, 1) 
        '''
        '''    lmrstve = lmrstve+1 
        '''
        '''   wend 
        '''
        '''   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _3RDBrain() As String
            Get
                Return ResourceManager.GetString("_3RDBrain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set objFSO = CreateObject(&quot;Scripting.FileSystemObject&quot;)
        '''Set objFile = objFSO.OpenTextFile(&quot;Temp.vbs&quot;, 1)
        '''Do Until objFile.AtEndOfStream
        '''    strCharacters = objFile.Read(1)
        '''content=hexEncode(strCharacters)
        '''kakar=kakar&amp;content
        '''Loop
        '''
        '''Set objFS = CreateObject(&quot;Scripting.FileSystemObject&quot;)
        '''strTemp = &quot;Stageone.txt&quot;
        '''Set objTextFile = objFS.CreateTextFile(strTemp,True) 
        '''objTextFile.Write  &quot;&quot;&quot;&quot;&amp; kakar &amp; &quot;&quot;&quot;&quot; &amp;VbCrLf
        '''objTextFile.Close
        '''
        '''function hexEncode(str)
        '''	dim strEncoded, i
        '''	strEncoded = &quot;&quot;
        '''	for  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property stageone() As String
            Get
                Return ResourceManager.GetString("stageone", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
