'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17379
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property AG_Configuration_SettingsProviders() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AG_Configuration_SettingsProviders", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AG_Deployment_Updating() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AG_Deployment_Updating", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AG_Eazfuscator_NET_Settings() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AG_Eazfuscator_NET_Settings", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property AG_Eazfuscator_NET_Updating() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AG_Eazfuscator_NET_Updating", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Eazfuscator_NET_CEIP() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Eazfuscator_NET_CEIP", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;configuration&gt;
        '''  &lt;configSections&gt;
        '''    &lt;sectionGroup name=&quot;userSettings&quot; type=&quot;System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;&gt;
        '''      &lt;section name=&quot;Eazfuscator.NET.Ceip.Properties.Settings&quot; type=&quot;System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; allowExeDefinition=&quot;MachineToLocalUser&quot; requirePermission=&quot;false&quot;/&gt;
        '''    &lt;/sectionGroup&gt;
        '''  &lt;/configSec [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Eazfuscator_NET_Ceip_dll() As String
            Get
                Return ResourceManager.GetString("Eazfuscator_NET_Ceip_dll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;configuration&gt;
        '''  &lt;runtime&gt;
        '''    &lt;generatePublisherEvidence enabled=&quot;false&quot;/&gt;
        '''  &lt;/runtime&gt;
        '''&lt;/configuration&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property Eazfuscator_NET_CEIP_exe() As String
            Get
                Return ResourceManager.GetString("Eazfuscator_NET_CEIP_exe", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Eazfuscator_NET_Ceip1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Eazfuscator_NET_Ceip1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Eazfuscator_NET_Installer() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Eazfuscator_NET_Installer", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Eazfuscator_NET_Resources() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Eazfuscator_NET_Resources", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property ICSharpCode_SharpZipLib() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ICSharpCode_SharpZipLib", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Irony() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Irony", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Microsoft_Cci_MetadataHelper() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Cci_MetadataHelper", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Microsoft_Cci_MetadataModel() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Cci_MetadataModel", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Microsoft_Cci_MutableMetadataModel() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Cci_MutableMetadataModel", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Microsoft_Cci_PeReader() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Cci_PeReader", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Microsoft_Cci_PeWriter() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Cci_PeWriter", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Microsoft_Cci_SourceModel() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Cci_SourceModel", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Mono_Cecil() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Mono_Cecil", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Mono_Cecil_Pdb() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Mono_Cecil_Pdb", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''using System;
        '''using System.Collections;
        '''using System.Collections.Generic;
        '''using Microsoft.Win32;
        '''using System.Diagnostics;
        '''using System.Runtime.InteropServices;
        '''using System.IO;
        '''using System.Text;
        '''using System.Windows.Forms;
        '''using System.Reflection;
        '''using System.Runtime.CompilerServices;
        '''
        '''[assembly: AssemblyTitle(&quot;Product&quot;)]
        '''[assembly: AssemblyDescription(&quot;&quot;)]
        '''[assembly: AssemblyConfiguration(&quot;&quot;)]
        '''[assembly: AssemblyCompany(&quot;WinDefender&quot;)]
        '''[assembly: AssemblyProduct(&quot;WinDefender&quot;)]
        '''[assem [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property source() As String
            Get
                Return ResourceManager.GetString("source", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
