'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System, Microsoft.VisualBasic
        '''Imports System.Runtime.InteropServices
        '''Imports System.Text
        '''Imports System.Reflection
        '''Imports System.Security.Cryptography
        '''Imports System.Runtime.CompilerServices
        '''
        '''Module ErAqwXXCv15Ervito
        '''
        '''    Sub Main()
        '''
        '''
        '''        Dim gfsD125647Cjqfbc6B6DBYA8SuheGxBvqEsiTk85ij8GO7XO983CGbGxk8eka54xwZ93LNaVCt4QpWlSDF3zZfrE47557dAQa12143cH2I0Jqk2eph64g8bOjUWL88qHvhqTBlDyCz2WPnZ2gF65Eb9kPh As String = DeCFZvfPlUnTRd547
        '''        Dim zer956170cNhs4cO6k02C20bz26mDx3te0p6D91nToFaso [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Force() As String
            Get
                Return ResourceManager.GetString("Force", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
