'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yellow")>  _
        Public Property SeleCor() As Global.System.Drawing.Color
            Get
                Return CType(Me("SeleCor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("SeleCor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SeleGridLins() As Boolean
            Get
                Return CType(Me("SeleGridLins"),Boolean)
            End Get
            Set
                Me("SeleGridLins") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MostrarInformações() As Boolean
            Get
                Return CType(Me("MostrarInformações"),Boolean)
            End Get
            Set
                Me("MostrarInformações") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MostrarDesktop() As Boolean
            Get
                Return CType(Me("MostrarDesktop"),Boolean)
            End Get
            Set
                Me("MostrarDesktop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MostrarNotificação() As Boolean
            Get
                Return CType(Me("MostrarNotificação"),Boolean)
            End Get
            Set
                Me("MostrarNotificação") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>354835|Temporários|11/01/2016|</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>265449|Testes|11/01/201"& _ 
            "6|</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>623598|Usuários|11/01/2016|</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>415764|Fa"& _ 
            "voritos|11/01/2016|</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property MeusGupos() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("MeusGupos"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("MeusGupos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property MyBodyColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MyBodyColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("MyBodyColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("WindowFrame")>  _
        Public Property MyBorderColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MyBorderColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("MyBorderColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("WindowFrame")>  _
        Public Property MyButtonBorderColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MyButtonBorderColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("MyButtonBorderColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Highlight")>  _
        Public Property MyButtonHoverColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MyButtonHoverColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("MyButtonHoverColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property MyContentColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MyContentColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("MyContentColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("HotTrack")>  _
        Public Property MyContentHoverColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MyContentHoverColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("MyContentHoverColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlDark")>  _
        Public Property MyHeaderColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MyHeaderColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("MyHeaderColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gray")>  _
        Public Property MyTitleColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MyTitleColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("MyTitleColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MyMostrarIcone() As Boolean
            Get
                Return CType(Me("MyMostrarIcone"),Boolean)
            End Get
            Set
                Me("MyMostrarIcone") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MyMostrarBotaodeFechar() As Boolean
            Get
                Return CType(Me("MyMostrarBotaodeFechar"),Boolean)
            End Get
            Set
                Me("MyMostrarBotaodeFechar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MyMostrarMenudeOpcoes() As Boolean
            Get
                Return CType(Me("MyMostrarMenudeOpcoes"),Boolean)
            End Get
            Set
                Me("MyMostrarMenudeOpcoes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MyMostrarGrip() As Boolean
            Get
                Return CType(Me("MyMostrarGrip"),Boolean)
            End Get
            Set
                Me("MyMostrarGrip") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MyEfeito() As Boolean
            Get
                Return CType(Me("MyEfeito"),Boolean)
            End Get
            Set
                Me("MyEfeito") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3000")>  _
        Public Property MyDuracao() As Integer
            Get
                Return CType(Me("MyDuracao"),Integer)
            End Get
            Set
                Me("MyDuracao") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property MyIntervalodeAnimacao() As Integer
            Get
                Return CType(Me("MyIntervalodeAnimacao"),Integer)
            End Get
            Set
                Me("MyIntervalodeAnimacao") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
        Public Property MyDuracaodaAnimacao() As Integer
            Get
                Return CType(Me("MyDuracaodaAnimacao"),Integer)
            End Get
            Set
                Me("MyDuracaodaAnimacao") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MyTituloPadding() As Integer
            Get
                Return CType(Me("MyTituloPadding"),Integer)
            End Get
            Set
                Me("MyTituloPadding") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MyDescricaoPadding() As Integer
            Get
                Return CType(Me("MyDescricaoPadding"),Integer)
            End Get
            Set
                Me("MyDescricaoPadding") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MyIconePadding() As Integer
            Get
                Return CType(Me("MyIconePadding"),Integer)
            End Get
            Set
                Me("MyIconePadding") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Área de Trabalho")>  _
        Public Property ÁreadeTrabalho() As String
            Get
                Return CType(Me("ÁreadeTrabalho"),String)
            End Get
            Set
                Me("ÁreadeTrabalho") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Área de Trabalho")>  _
        Public Property MinhaAreaDeTrabalho() As String
            Get
                Return CType(Me("MinhaAreaDeTrabalho"),String)
            End Get
            Set
                Me("MinhaAreaDeTrabalho") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Coringa.My.MySettings
            Get
                Return Global.Coringa.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
