'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RemoteDesktop.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MaybehBanner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaybehBanner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;configuration&gt;
        '''  &lt;appSettings&gt;
        '''    &lt;add key=&quot;LSHOW&quot; value=&quot;YES&quot; /&gt;
        '''    &lt;add key=&quot;IP&quot; value=&quot;&quot; /&gt;
        '''    &lt;add key=&quot;ISMSG&quot; value=&quot;&quot; /&gt;
        '''    &lt;add key=&quot;MSGTITLE&quot; value=&quot;&quot; /&gt;
        '''    &lt;add key=&quot;MSGBODY&quot; value=&quot;&quot; /&gt;
        '''    &lt;add key=&quot;INSTALL&quot; value=&quot;&quot; /&gt;
        '''    &lt;add key=&quot;ANTI&quot; value=&quot;&quot; /&gt;
        '''    &lt;add key=&quot;NOIPSAVE&quot; value=&quot;YES&quot; /&gt;
        '''     &lt;add key=&quot;NOTIFY&quot; value=&quot;YES&quot; /&gt;
        '''    &lt;add key=&quot;NOIPUSERNAME&quot; value=&quot;&quot; /&gt;
        '''    &lt;add key=&quot;NOIPPASSWORD&quot; value=&quot;&quot; /&gt;
        '''    &lt;add key=&quot;NOIPHOST&quot; value=&quot;&quot;  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
